import Head from 'next/head';
import TextC from '../components/textC';
import TreeC from '../components/treeC';


export default function MainPage() {
    return (
    <><Head>
        <title>SPOTYFIND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/3844/3844724.png" />

    </Head>

    <div>
        <main>
            <TreeC />
            <TextC />
        </main>

        
    </div>
    </>
);
    }
